title: Thinking Out Louder
description: "Guanjie Li's notes on minds, machines, and the users between them"
lang: en-US

url: "https://guanjie.li"
baseurl: "/Thinking-out-louder"

repository: LiYou0719/Thinking-out-louder

owner:
  name: Guanjie Li
  linkedin: https://www.linkedin.com/in/guanjie-li-5997b980/

author:
  name: Guanjie Li
  url: https://guanjie.li

goatcounter: moxslee

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
