title: Thinking Out Louder
description: "Guanjie's notes on minds, machines, and the users between them"

url: "https://LiYou0719.github.io"
baseurl: "/Thinking-out-louder"

repository: LiYou0719/Thinking-out-louder

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
