title: Thinking Out Louder
description: "Guanjie Li's notes on minds, machines, and the users between them"

url: "https://liyou0719.github.io"
baseurl: "/Thinking-out-louder"

repository: LiYou0719/Thinking-out-louder

owner:
  name: Guanjie Li
  linkedin: https://www.linkedin.com/in/guanjie-li-5997b980/

goatcounter: moxslee

theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
